"""The declarative base and the schema everything lives in.

**Why a dedicated ``promisepatch`` schema rather than ``public``.** A managed PostgreSQL host
may expose ``public`` through an automatic REST layer, where a table without row-level
security is readable by anyone holding the project's anonymous key. PromisePatch holds
customer names, order contents and an audit ledger; none of that should depend on remembering
to enable RLS on every future table. A private schema removes the exposure by construction and
costs one qualified name. It is also where the audited-write trigger functions will live.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

SCHEMA = "promisepatch"

NAMING_CONVENTION = {
    "pk": "pk_%(table_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
}
"""Deterministic constraint names.

Autogenerated names cannot be referenced by a later migration, and an unnamed ``CHECK`` that
fires in production tells an operator nothing. Every constraint here is named, so a violation
message names the rule that produced it.
"""

metadata = MetaData(schema=SCHEMA, naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Declarative base for every PromisePatch table."""

    metadata = metadata
